# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Charbel/Documents/ECE_520/space_invaders_soc/space_invaders_soc.srcs/sources_1/bd/space_invaders_bd/ip/space_invaders_bd_auto_pc_0/space_invaders_bd_auto_pc_0.xci
# IP: The module: 'space_invaders_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Charbel/Documents/ECE_520/space_invaders_soc/space_invaders_soc.gen/sources_1/bd/space_invaders_bd/ip/space_invaders_bd_auto_pc_0/space_invaders_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'space_invaders_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Charbel/Documents/ECE_520/space_invaders_soc/space_invaders_soc.srcs/sources_1/bd/space_invaders_bd/ip/space_invaders_bd_auto_pc_0/space_invaders_bd_auto_pc_0.xci
# IP: The module: 'space_invaders_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Charbel/Documents/ECE_520/space_invaders_soc/space_invaders_soc.gen/sources_1/bd/space_invaders_bd/ip/space_invaders_bd_auto_pc_0/space_invaders_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'space_invaders_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
